### PR TITLE
Update vendored assets from RAML 1.0 feature branch of api-console

### PR DESCRIPTION
**Pull request by danielocallaghan**
@matt-wratt @gingermusketeer would be great if you could have a look at this though its not ready to merge as I'm getting some wierd js errors locally from attempting to include files dynamically which don't exist.. think I've done something wrong or the lastest version that i've updated to (via the `bin/update` script) isn't compatible somehow.. the error i'm seeing in the rails logs:

```
[faa4ac40-7df8-4c26-83bc-692837a710a0] [No Consumer]
ActionController::RoutingError (No route matches [GET] "/assets/raml_console/map.js.map"):
  actionpack (4.2.5.2) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
```

so its trying to load: `map.js.map`  which the only reference to which is deep within `api-console-vendor.js` line: 361565

```

    'use strict';
    var Type = __webpack_require__(188);
    module.exports = new Type('tag:yaml.org,2002:map', {
        kind: 'mapping',
        construct: function (data) { return null !== data ? data : {}; }
    });
    //# sourceMappingURL=map.js.map
```

Any help much appreciated!

### CODE REVIEW

**Comment by gingermusketeer** [comment]
@danielocallaghan My suspicion is that the map needs to include a hash. What filename for the map do you get when the assets are precompiled?

**Comment by danielocallaghan** [comment]
@gingermusketeer hmm precompiling the assets... thats a novel idea indeed! 
will try that and see how I go cheers.

**Comment by danielocallaghan** [comment]
hey @gingermusketeer so for 'precompiling the assets' how would I actually go about trying to do that? (thought I knew but think i am off track...)

**Comment by danielocallaghan** [comment]
from what I can tell it looks like the `dist/` folder should contain precompiled assets but looks like api-console-vendor.js has a bunch of references to things like:

```
        /// <reference path="../typings/main.d.ts" />
        var invariant = __webpack_require__(13);

```

cc @lukemcfarlane @matt-wratt let me know if you have any ideas...

**Pull request closed without merging**
